'use client';

import { useMemo, useState } from 'react';
import { products as seedProducts, reviews } from '@/data/products';
import { Button } from '@/components/ui/button';
import { formatMoney } from '@/lib/utils';

type Mode = 'overview' | 'products' | 'orders' | 'reviews' | 'homepage' | 'coupons' | 'subscribers';

export function AdminManager({ mode }: { mode: Mode }) {
  const [products, setProducts] = useState(seedProducts);
  const [draft, setDraft] = useState({ title: '', price: 0, category: 'handmade-gifts' });
  const orders = useMemo(() => [
    { order: 'DBD-TEST01', customer: 'Gift Buyer', status: 'pending_payment', total: 115, note: 'Please include a handwritten gift note.' },
    { order: 'DBD-TEST02', customer: 'Hospital Donation Inquiry', status: 'in_review', total: 9, note: 'Bulk port pillow donation question.' }
  ], []);
  const subscribers = ['buyer@example.com', 'caregiver@example.com', 'giftideas@example.com'];

  if (mode === 'overview') return <div className="grid gap-4 md:grid-cols-4">{[['Products', products.length], ['Orders', orders.length], ['Reviews', reviews.length], ['Subscribers', subscribers.length]].map(([label, value]) => <div key={String(label)} className="rounded-[2rem] bg-white/70 p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-[0.2em] text-honeyDark">{label}</p><p className="mt-4 font-serif text-5xl">{String(value)}</p></div>)}</div>;

  if (mode === 'products') return <div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><form className="h-fit rounded-[2rem] bg-white/70 p-6 shadow-soft" onSubmit={(e) => { e.preventDefault(); if (!draft.title) return; setProducts((current) => [{ ...seedProducts[0], id: `prod_${Date.now()}`, slug: draft.title.toLowerCase().replace(/[^a-z0-9]+/g, '-'), title: draft.title, price: Number(draft.price), category: draft.category as any, collections: [draft.category as any], featured: false }, ...current]); setDraft({ title: '', price: 0, category: 'handmade-gifts' }); }}><h2 className="font-serif text-3xl">Add product</h2><input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} placeholder="Product title" className="mt-5 w-full rounded-2xl border border-ink/10 px-4 py-3" /><input value={draft.price} onChange={(e) => setDraft({ ...draft, price: Number(e.target.value) })} placeholder="Price" type="number" className="mt-3 w-full rounded-2xl border border-ink/10 px-4 py-3" /><select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })} className="mt-3 w-full rounded-2xl border border-ink/10 px-4 py-3"><option>handmade-gifts</option><option>mastectomy-recovery-gifts</option><option>port-pillows</option><option>personalized-ornaments</option></select><Button type="submit" className="mt-4 w-full">Add demo product</Button></form><div className="rounded-[2rem] bg-white/70 p-6 shadow-soft"><h2 className="mb-5 font-serif text-3xl">Products</h2><div className="space-y-3">{products.map((product) => <div key={product.id} className="flex items-center justify-between gap-4 rounded-2xl bg-cream p-4"><div><p className="font-semibold">{product.title}</p><p className="text-sm text-ink/55">{formatMoney(product.price)} · {product.category}</p></div><div className="flex gap-2"><button onClick={() => setProducts((current) => current.map((item) => item.id === product.id ? { ...item, featured: !item.featured } : item))} className="rounded-full bg-white px-3 py-2 text-xs font-bold">{product.featured ? 'Unfeature' : 'Feature'}</button><button onClick={() => setProducts((current) => current.filter((item) => item.id !== product.id))} className="rounded-full bg-ink px-3 py-2 text-xs font-bold text-ivory">Delete</button></div></div>)}</div></div></div>;

  if (mode === 'orders') return <div className="rounded-[2rem] bg-white/70 p-6 shadow-soft"><h2 className="mb-5 font-serif text-3xl">Orders</h2><table className="w-full text-left text-sm"><thead><tr className="border-b border-ink/10"><th className="py-3">Order</th><th>Customer</th><th>Status</th><th>Total</th><th>Gift note</th></tr></thead><tbody>{orders.map((order) => <tr key={order.order} className="border-b border-ink/10"><td className="py-4 font-bold">{order.order}</td><td>{order.customer}</td><td><select defaultValue={order.status} className="rounded-full bg-cream px-3 py-2"><option>pending_payment</option><option>paid</option><option>in_production</option><option>shipped</option><option>cancelled</option></select></td><td>{formatMoney(order.total)}</td><td>{order.note}</td></tr>)}</tbody></table></div>;

  if (mode === 'reviews') return <div className="grid gap-4 md:grid-cols-2">{reviews.map((review) => <div key={review.product} className="rounded-[2rem] bg-white/70 p-6 shadow-sm"><p className="text-honey">★★★★★</p><p className="mt-3 font-serif text-2xl">“{review.excerpt}”</p><p className="mt-3 text-sm text-ink/55">{review.name} · {review.product}</p><Button variant="secondary" className="mt-4">Toggle featured</Button></div>)}</div>;

  if (mode === 'homepage') return <div className="rounded-[2rem] bg-white/70 p-6 shadow-soft"><h2 className="font-serif text-3xl">Homepage controls</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{['Hero headline', 'Featured products', 'Donation section'].map((item) => <label key={item} className="rounded-2xl bg-cream p-4"><span className="block text-sm font-bold">{item}</span><textarea defaultValue={item === 'Hero headline' ? 'Handmade gifts for healing, comfort, and meaningful moments.' : 'Enabled'} className="mt-2 min-h-28 w-full rounded-2xl border border-ink/10 p-3" /></label>)}</div><Button className="mt-5">Save homepage draft</Button></div>;

  if (mode === 'coupons') return <div className="rounded-[2rem] bg-white/70 p-6 shadow-soft"><h2 className="font-serif text-3xl">Discount codes</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><input placeholder="Code" className="rounded-2xl border border-ink/10 px-4 py-3" /><input placeholder="Percent off" type="number" className="rounded-2xl border border-ink/10 px-4 py-3" /><Button>Create coupon</Button></div><p className="mt-4 text-sm text-ink/60">Coupon table and Stripe promotion-code sync are ready to wire in `supabase/schema.sql`.</p></div>;

  return <div className="rounded-[2rem] bg-white/70 p-6 shadow-soft"><h2 className="font-serif text-3xl">Email subscribers</h2><div className="mt-5 space-y-3">{subscribers.map((email) => <div key={email} className="rounded-2xl bg-cream px-4 py-3 font-semibold">{email}</div>)}</div><Button className="mt-5">Export CSV</Button></div>;
}
